-- Discount/voucher codes: general_manager creates codes from the Staff
-- Portal, customers redeem one at checkout. Real usage-cap enforcement
-- happens server-side inside create_order_with_items (below) so a race
-- between two customers on the last remaining use can't both win, and a
-- client can never fabricate its own discount amount - the same "recompute
-- everything server-side, never trust the client" rule this function
-- already follows for prices.
create table public.vouchers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value numeric not null check (discount_value > 0),
  -- percentage caps at 100 (a 150%-off code makes no sense); fixed has no
  -- upper bound here since it's already clamped to the order subtotal at
  -- redemption time below.
  constraint vouchers_percentage_range check (discount_type <> 'percentage' or discount_value <= 100),
  max_uses integer check (max_uses is null or max_uses > 0),
  used_count integer not null default 0,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_by uuid references public.users(id),
  created_at timestamptz not null default now()
);

alter table public.vouchers enable row level security;

-- No anon/authenticated grant at all: the full list (codes, remaining
-- uses, discount amounts) is exactly what a scraper would want, so staff
-- management reads/writes go through the table directly under RLS, and
-- everything a customer needs (validity + resulting discount, never the
-- underlying code list) goes through check_voucher below instead.
grant select, insert, update, delete on public.vouchers to authenticated;

create policy "vouchers_all_general_manager"
  on public.vouchers for all
  to authenticated
  using (current_user_role()::text = 'general_manager' and current_user_is_active())
  with check (current_user_role()::text = 'general_manager' and current_user_is_active());

alter table public.orders add column if not exists voucher_code text;
alter table public.orders add column if not exists discount_amount numeric not null default 0;

-- Read-only preview for the checkout UI - never redeems (no used_count
-- change), so it's safe to call as many times as the customer edits the
-- code field. Real redemption only ever happens inside
-- create_order_with_items, atomically with the order itself.
create or replace function public.check_voucher(p_code text, p_subtotal numeric)
returns table(valid boolean, discount_amount numeric, reason text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_voucher record;
  v_discount numeric;
begin
  select * into v_voucher from public.vouchers where code = upper(trim(p_code));

  if v_voucher is null then
    return query select false, 0::numeric, 'الكود ده مش موجود';
    return;
  end if;
  if not v_voucher.is_active then
    return query select false, 0::numeric, 'الكود ده مش شغال دلوقتي';
    return;
  end if;
  if v_voucher.expires_at is not null and v_voucher.expires_at < now() then
    return query select false, 0::numeric, 'الكود ده منتهي الصلاحية';
    return;
  end if;
  if v_voucher.max_uses is not null and v_voucher.used_count >= v_voucher.max_uses then
    return query select false, 0::numeric, 'الكود ده خلص استخدامه';
    return;
  end if;

  if v_voucher.discount_type = 'percentage' then
    v_discount := round(p_subtotal * v_voucher.discount_value / 100, 2);
  else
    v_discount := least(v_voucher.discount_value, p_subtotal);
  end if;

  return query select true, v_discount, null::text;
end;
$$;

revoke execute on function public.check_voucher(text, numeric) from public, anon;
grant execute on function public.check_voucher(text, numeric) to authenticated;

-- create_order_with_items (0056) extended with two new trailing params.
-- Postgres treats added parameters as a new overload, not a true replace -
-- CREATE OR REPLACE alone would leave the old 11-arg signature callable
-- alongside this one and ambiguous for PostgREST's named-arg RPC calls, so
-- the old signature is dropped explicitly first. That drop also resets
-- this function back to Postgres's default PUBLIC-EXECUTE grant, which is
-- exactly the CRIT-2 hole 0058 closed - re-revoked explicitly below so
-- this migration can't silently reopen it.
drop function if exists public.create_order_with_items(text, bigint, uuid, text, bigint, text, text, numeric, text, integer, jsonb);

-- Voucher validation + the atomic used_count increment happen here,
-- inside the same transaction as the order/items insert: if the code
-- turns out invalid/expired/exhausted by the time this runs, the whole
-- function raises and nothing commits, exactly like every other
-- validation failure in here.
create or replace function public.create_order_with_items(
  p_order_source text,
  p_branch_id bigint,
  p_customer_id uuid,
  p_customer_phone text,
  p_address_id bigint,
  p_payment_method text,
  p_payment_proof_url text,
  p_delivery_fee numeric,
  p_delivery_service text,
  p_delivery_time_minutes int,
  p_items jsonb,
  p_voucher_code text default null,
  p_subtotal numeric default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
  v_voucher record;
  v_discount numeric := 0;
begin
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'p_items must be a non-empty JSON array';
  end if;

  if p_voucher_code is not null then
    -- Row lock: two concurrent redemptions of the same near-exhausted
    -- voucher serialize on this SELECT instead of both reading
    -- used_count=max_uses-1 and both succeeding.
    select * into v_voucher from public.vouchers where code = upper(trim(p_voucher_code)) for update;

    if v_voucher is null then
      raise exception 'voucher code not found';
    end if;
    if not v_voucher.is_active then
      raise exception 'voucher code is not active';
    end if;
    if v_voucher.expires_at is not null and v_voucher.expires_at < now() then
      raise exception 'voucher code has expired';
    end if;
    if v_voucher.max_uses is not null and v_voucher.used_count >= v_voucher.max_uses then
      raise exception 'voucher code has no uses remaining';
    end if;

    if v_voucher.discount_type = 'percentage' then
      v_discount := round(coalesce(p_subtotal, 0) * v_voucher.discount_value / 100, 2);
    else
      v_discount := least(v_voucher.discount_value, coalesce(p_subtotal, 0));
    end if;

    update public.vouchers set used_count = used_count + 1 where id = v_voucher.id;
  end if;

  insert into public.orders (
    order_source, branch_id, customer_id, customer_phone, address_id,
    status, order_time, payment_method, payment_proof_url,
    delivery_fee_after_tax, delivery_service, delivery_time_minutes,
    voucher_code, discount_amount
  ) values (
    p_order_source::order_source_type, p_branch_id, p_customer_id, p_customer_phone, p_address_id,
    'pending_acceptance', now(), p_payment_method::payment_method_type, p_payment_proof_url,
    p_delivery_fee, p_delivery_service, p_delivery_time_minutes,
    case when p_voucher_code is not null then upper(trim(p_voucher_code)) else null end, v_discount
  )
  returning id into v_order_id;

  insert into public.order_items (order_id, menu_item_id, combo_offer_id, quantity, unit_price, combo_selection, note)
  select
    v_order_id,
    (item->>'menu_item_id')::bigint,
    (item->>'combo_offer_id')::bigint,
    (item->>'quantity')::int,
    (item->>'unit_price')::numeric,
    item->>'combo_selection',
    item->>'note'
  from jsonb_array_elements(p_items) as item;

  return v_order_id;
end;
$$;

-- Re-applied after the drop+recreate above (see comment there) - CRIT-2:
-- only service_role (the create-order edge function's admin client) may
-- ever call this directly.
revoke execute on function public.create_order_with_items(text, bigint, uuid, text, bigint, text, text, numeric, text, integer, jsonb, text, numeric) from public, anon, authenticated;
